# Generated by Django 4.2.17 on 2025-01-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(default='stories/images/default_2.jpg', upload_to='stories/images'),
        ),
    ]
